{% set name = "napari-allencell-annotator" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-allencell-annotator-{{ version }}.tar.gz
  sha256: 7e57f748bda9dad5a7e198b29f9a7603206dafadb1722fc1d1462581c093166e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - aicsimageio >=4.0.5
    - aicssegmentation >=0.4.1
    - magicgui >=0.2.9
    - napari >=0.4.9
    - napari-plugin-engine >=0.1.4
    - numpy
    - psygnal
    - python >=3.7
    - qtpy

test:
  imports:
    - napari_allencell_annotator
  commands:
    - pip list
    # - pip check  # itk-meshtopolydata and aicssegmentation
  requires:
    - pip

about:
  home: https://github.com/aics-int/napari-allencell-annotator/
  summary: A plugin that enables annotations provided by Allen Institute for Cell Science
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
